import Head from "next/head";
import Form from "../../../components/form/form";
import Image from "../../../components/image";
import PricingCell from "../../../components/pricingCell";
import SolutionsItem from "../../../components/solutions/solutionsItem";
import SolutionsItem2 from "../../../components/solutions/solutionsItem2";
import SolutionsPageWrapper from "../../../components/solutions/solutionsPageWrapper";

export default function AIMachineLearning() {
    return <div className="">
        <Head>
            <title key="title">Sapphire - AI</title>
            <meta name="keywords" id="keywords" content="Portland AI Company,Artificial Intelligence,Portland Machine Learning,Portland Oregon AI Software" />
        </Head>
        <SolutionsPageWrapper title="AI Machine Learning" desc="Breakthroughs in AI have opened the door for new business oportunities. The engineers at Sapphire have been watching trends in the industry for some time and are experts at utilizing these new technologies in novel ways for your business." src="/svg/chat-bot.svg" alt="Chat Bot" moreTag="#why">
            <div className="space-y-16 nd:space-y-32">
                <div className="grid place-items-center gap-8">
                    <Image props={{
                        src: "/images/dalle2-sapphire-dev.png",
                        alt: "DALLE2 generated image",
                        divClass: "max-w-[600px] overflow-clip rounded-md",
                        imgClass: ""
                    }} />
                    <p className="subtext text-base max-w-xl text-center">Generated by OpenAI DALLE-2, &quot;Sapphire development for the modern world painting&quot;</p>
                </div>
                <SolutionsItem description="How We Can Use AI" id="why" hasHeight={false}>
                    <div className="space-y-16 pt-16">
                        <SolutionsItem2 title={"SEO Blog Generation"} desc={"Some content can be generated relatively easily with little need for input. One such use case is for generating blog posts to boost a website's SEO rating."} id={"#seo-content-generation"}>
                            <Image props={{
                                src: "/svg/search-engines.svg",
                                alt: "Search Engine SEO",
                                divClass: "max-w-[400px]",
                                imgClass: ""
                            }} />
                        </SolutionsItem2>
                        <SolutionsItem2 title={"Content Generation"} reverse={true} desc={"Using existing business information, other content can be generated as well. For example, a client teaching classes is now able to use a book they authored to automatically generate test questions."} id={"#content-generation"}>
                            <Image props={{
                                src: "/svg/online-learning.svg",
                                alt: "Exam question generation",
                                divClass: "max-w-[400px]",
                                imgClass: ""
                            }} />
                        </SolutionsItem2>
                        <SolutionsItem2 title={"Classification"} reverse={false} desc={"We have extensive experience constructing neural networks to aid in classification tasks. These can range from images, text, database data, customer data, and more."} id={"#classification"}>
                            <Image props={{
                                src: "/svg/classification.svg",
                                alt: "Neural network analysis",
                                divClass: "max-w-[400px]",
                                imgClass: ""
                            }} />
                        </SolutionsItem2>
                    </div>
                </SolutionsItem>
                <SolutionsItem description="Technologies We Use" id="technologies" hasHeight={false}>
                    <div className="space-y-16 pt-16">
                        <SolutionsItem2 title={"Neural Networks"} desc={"A classic machine learning algorithm, we have experience using packages such as Tensorflow, Scipy, and Pytorch. In addition, our engineers have experience constructing these algorithms from scratch, A live example can be found at nn.jakelanders.com."} id={"#seo-content-generation"}>
                            <Image props={{
                                src: "/images/neural-network.png",
                                alt: "Neural Network",
                                divClass: "max-w-[400px]",
                                imgClass: ""
                            }} />
                        </SolutionsItem2>
                        <SolutionsItem2 title={"Open AI GPT-3"} reverse={true} desc={"We are well versed in utilizing the powerful models released by OpenAI. AI prompting and API usage are becoming increasingly important, rely on the experts to make the most of these technologies."} id={"#openai-gpt3"}>
                            <Image props={{
                                src: "/images/openai.png",
                                alt: "Open AI GPT-3",
                                divClass: "max-w-[400px]",
                                imgClass: ""
                            }} />
                        </SolutionsItem2>
                        <SolutionsItem2 title={"Language Models"} reverse={false} desc={"Bloom is an interesting new open source alternative to GPT-3. Due to its open nature, it allows for the ability to self host the technology with unlimited use."} id={"#language-models"}>
                            <Image props={{
                                src: "/images/bloom.png",
                                alt: "Bloom Language Model",
                                divClass: "max-w-[400px] overflow-clip rounded-md",
                                imgClass: ""
                            }} />
                        </SolutionsItem2>
                    </div>
                </SolutionsItem>
                <div id="pricing" className="pt-16">
                    <h3 className="grid place-items-center subtitle pb-16">Pricing</h3>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <PricingCell props={{
                            title: "Estimate",
                            price: "Free",
                            description: "Talk with an engineer about your needs.",
                            points: ["No commitment", "No upselling", "Convenient scheduling", "Guided conversation"],
                            isMonthly: false
                        }} />
                        <PricingCell props={{
                            title: "Consulting",
                            price: "$50",
                            description: "Consult an expert for design decisions.",
                            points: ["Experts in the ML field", "Knowlegable on many approaches", "Well connected in industry", "Collaboration on solutions"],
                            isMonthly: true,
                            isFrom: false,
                        }} />
                        <PricingCell props={{
                            title: "AI Solution",
                            price: "Contact",
                            description: "Deployment of a machine learning product.",
                            points: ["Purpose built", "Unique problems and soltutions", "Unique integrations", "First-class support"],
                            isMonthly: false,
                            isFrom: false,
                        }} />
                    </div>
                </div>
                <Form props={{
                    nameLabel: undefined,
                    emailLabel: undefined,
                    bodyLabel: "Talk with us about messaging systems systems",
                    tag: "AI Machine Learning"
                }} />
            </div>
        </SolutionsPageWrapper>
    </div>
}